dependencies:
  - numpy
  - nbconvert
  - nbformat
# - nbinteract
# - traitlets
# - toolz
# - docopt
# - Jinja2
# - datascience
  - bqplot
  - ipywidgets
  - scipy
  - pandas
  - seaborn
  - statsmodels
  - matplotlib
