channels:
  - defaults
dependencies:
  - ipython
  - ipywidgets
  - matplotlib
  - bqplot
  - numpy
  - scipy
  - 'git+https://github.com/pandas-dev/pandas.git'
  - seaborn
  - statsmodels
  - matplotlib
