channels:
  - defaults
dependencies:
  - ipython
  - ipywidgets
  - matplotlib
  - bqplot
  - numpy
  - scipy
  - pandas
  - seaborn
  - statsmodels
  - matplotlib
# - nbconvert
# - nbformat
# - nbinteract
# - traitlets
# - toolz
# - docopt
# - Jinja2
# - datascience
